### ISSUE TITLE
Random initialized data structure 

### ISSUE THREAD

**Issue by asmaa899** [Alusus/Alusus#229]
Hi
I'm just trying to write [raylib5](https://github.com/raysan5/raylib/tree/5.0) bindings for alusus programming language
Basically I wrote a simple example file and it corresponding binding functions to detect any early issues before I go farther. The file is too similar to (https://github.com/raysan5/raylib/blob/5.0/examples/core/core_basic_window.c)

 I'm having a confused problem about `Color` data structure (bind to Alusus Color class)
I see rcore.clearBackground (corresponding to raylib ClearBackground) fills background with a new random color in every time the source file runs, same thing goes in rcore.drawText (corresponding to DrawText, requires also a `Color` struct): It draws it with a different color in every time the file runs.

I can't claim its been  initialized randomly (its in a while loop, this means that in every iteration sould make a different color with a massive old-TV animation), which isn't my case. It only in every diffrent execution of file, is making a different color (for both text and background)

the raylib (C) color struct is in : https://github.com/raysan5/raylib/blob/ae50bfa2cc569c0f8d5bc4315d39db64005b1b08/src/raylib.h#L238

Here is my code:
[raylib-alusus.zip](https://github.com/Alusus/Alusus/files/15155926/raylib-alusus.zip)

Random runs of the source:
![screenshot](https://github.com/Alusus/Alusus/assets/168238784/49abfa5a-a84d-4da2-a414-c01ab244a53e)
![screenshot](https://github.com/Alusus/Alusus/assets/168238784/2ca79e7d-4d6d-47a9-919c-932aad2b1eeb)

**Comment by sarmadka** [comment]
Hello,

This is probably an issue of pass-by-ref vs pass-by-value.  In Alusus, the compiler passes class values by reference if the class has user defined initialization (constructors and copy operations). Usually C does the same, but it looks like in this case the C compiler (with which raylib was built) decided that the Color structure is too simple that it's better to pass it by value. So, my guess is that Alusus compiler is passing a reference (pointer) and the C compiler is interpreting that as a value, hence the random behaviour.

You can fix this by converting the Color class in Alusus to a simple class, i.e. just remove the constructors and the assign handler.

The other issue you have is with the definition of Color. The Word type in Alusus is by default 32 bits, whereas Raylib defines it as bytes. So, you need to use Word[8] instead of Word. So, the Color class should look like this:

```
class Color {
    def r: Word[8];
    def g: Word[8];
    def b: Word[8];
    def a: Word[8];
}
```

If that doesn't fix the problem report back here and I'll help investigate the issue.

**Comment by asmaa899** [comment]
> ```
> class Color {
>     def r: Word[8];
>     def g: Word[8];
>     def b: Word[8];
>     def a: Word[8];
> }
> ```

In fact I've just got ride of the random color issue with this (simpler) definition
But another problem arise now: both text and background are totaly red~ (just if seems r=255 and a=255 and others totally zero


changing data types to Word[8],Int[8],Char all have the same problem:
```
def LIGHTGRAY: Color = Color () ;
LIGHTGRAY.r = 200;
LIGHTGRAY.g = 200;
LIGHTGRAY.b = 200;
LIGHTGRAY.a = 255;



def RAYWHITE :  Color = Color();;
 RAYWHITE.r = 245;
 RAYWHITE.g = 245;
 RAYWHITE.b = 245;
 RAYWHITE.a = 255;


rcore.clearBackground(rcore.LIGHTGRAY);
rcore.drawText("Congrats! You created your first window!", 190, 200, 20, rcore.RAYWHITE);
````

**Comment by asmaa899** [comment]
Ok added the following constructor:

```
    handler this~init() {
      this.r = 22;
      this.g = 0;
      this.b = 0;
      this.a = 255;
    
    }
I see the color changes but we still too far (when r is 25 and a is 255 I get some mix of green and blue). seems and until now the numbers are intepretted differently
If I changed `a` (alpha component) I get a new color mix (not changing alpha value)

**Comment by sarmadka** [comment]
Strange. Maybe the datatype of the color components in raylib isn't byte sized as I thought. I was looking at its definition here:
https://github.com/raysan5/raylib/blob/master/src/raylib.h#L241
Let me play around with it on my side and report back.

**Comment by sarmadka** [comment]
I did some experimentation and found some really unexpected behaviour where the function is only receiving the first member of the class, which is r, expanding that to 32 bits and ignoring the rest. Here is what I think is happening:
* The C compiler optimized the raylib struct (which has 4 byte sized vars) into a single 32 bit word.
* The linker linking Alusus program with raylib is doing more than just blind linking. I think it's looking at the compiled raylib and seeing that the function expects a Word and doesn't know that initially this was a struct, so it's trying to make sure it passes a word. When it sees a struct coming it's taking the first member of that struct, which is a Word[8] value, and casting it to Word32. As a result, whatever you set in the class only the red value is taken.

This is a bit of a strange behaviour from the linker, but anyway, there are two ways to work around it:

1- Define the function's Color argument as a Word, rather than Color, to match the actual compiled version of the raylib function, then provide a cast operator in the Color class. So your code in rcore.alusus will look like this:
```
class Color {
    def r: Word[8];
    def g: Word[8];
    def b: Word[8];
    def a: Word[8];

    handler this~cast[Word] return this~ptr~cast[ptr[Word]]~cnt;
}

def LIGHTGRAY: Color = Color().{ r=200; g=200; b=200; a=255 };
def RAYWHITE : Color = Color().{ r=245; g=245; b=245; a=255 };

@expname[ClearBackground]
function clearBackground (flags: Word);
```

What that `this~cast` operator is doing is: taking the pointer of `this`, then casting that pointer to a pointer to Word, then taking the content. As a result, this will take the same Color value bit by bit but present it to the compiler as a single Word value. The linker will then just past the word value as is to Raylib without any manipulation. You'll have to change any Color arg in all raylib functions to be of type Word instead of Color.

2- Change the definition of Color to define a single component word var to include all color components, then define properties for updating each individual color component. These properties will then do bit arithmetic to update the color components. This is a more complicated approach and I'm listing it here just for completeness, otherwise I think the first approach is better and less error prone. With this approach you don't have to change the color arg types in raylib functions to Word. Here is how your Color class would look:

```
class Color {
    def c: Word;

    handler this.r = Word[8] {
        this.c &= !255ui32;
        this.c |= value;
        return value;
    }
    handler this.r: Word[8] {
    	return this.c & 255;
    }

    handler this.g = Word[8] {
        this.c &= !(255ui32 << 8);
        this.c |= (value~cast[Word[32]] << 8);
        return value;
    }
    handler this.g: Word[8] {
    	return (this.c >> 8) & 255;
    }

    handler this.b = Word[8] {
        this.c &= !(255ui32 << 16);
        this.c |= (value~cast[Word[32]] << 16);
        return value;
    }
    handler this.b: Word[8] {
    	return (this.c >> 16) & 255;
    }

    handler this.a = Word[8] {
        this.c &= !(255ui32 << 24);
        this.c |= (value~cast[Word[32]] << 24);
        return value;
    }
    handler this.a: Word[8] {
    	return (this.c >> 24) & 255;
    }
}
```

Notice the following about this approach:
* We have to cast values from 8 bit to 32 bit BEFORE doing bit shifting, otherwise the bits will be dropped.
* The ! operator is a bitwise not (in Alusus ! is for bitwise not and !! is for logical not, just like & is for bitwise and and && is for logical and)
* The ui32 suffix in numbers specifies that the number is an unsigned 32 bit int. Without a suffix, Alusus compiler tries to find the smallest datatype that can hold the number. So, a value of 100 in Alusus is an 8 bit value, whereas a value of 10000 is a 16 bit number. Also, the result of (100 << 8) in Alusus would be 0! This is because 100 is 8 bit, and when you shift those 8 bits 8 steps to the left they are all dropped and you end up with 0.

I tested both methods, and they both worked.

**Comment by asmaa899** [comment]
Thanks Sarmad, I finally got final result
But however I'm afraid this code will not always reflect the real library file (and how much it compile-time optimized)

If I make the struct as behaves as specific/determined datatype, Does this making the whole binding (probably) unable to do correctly with different sets of C compiler optimizations ?


In addition, `Color` could be only the begining (:smile:) please have a look at the raylib structs there (nearly the bottom of the page) which could be more complex https://www.raylib.com/cheatsheet/cheatsheet.html  

I really noticed that classes in Alusus is completely binded by (redefiniting) them again as classes, but what if we could use something similar to `@expname` but for compounded datatype

I really find every struct has two copies (C/C++/.. ,Alusus) two compiled versions to be a topic of real linking issues (and wonder how it did come in the alreay existed binding)

**Comment by sarmadka** [comment]
> If I make the struct as behaves as specific/determined datatype, Does this making the whole binding (probably) unable to do correctly with different sets of C compiler optimizations ?

Alusus binding, like any binding in any other language, is dependent on struct padding or packing, which are compiler optimization methods to reduce the number of reads the CPU does from memory. Other optimization options doesn't affect the binding. The struct padding/packing is standard and deterministic so there shouldn't be a problem. In other words, the compiler doesn't behave different in different situations in this regard, so once you understand how the compiler treats non 32/64 bit values, you'll be able to apply your understanding to the rest of the structs regardless of their complexity.

Was the raylib binary built by you, or readily available? If you compiled it yourself then you can play with compiler flags to disable struct packing if you want, and that will make the binding more straight forward. But I personally don't think that's necessary.

> I really noticed that classes in Alusus is completely binded by (redefiniting) them again as classes, but what if we could use something similar to @expname but for compounded datatype

That's not possible as shared libraries don't include struct info, so there is no way for the compiler to extract that info from the shared library.

> I also find that a struct has two copies (C/C++/.. ,Alusus) two compiled versions to be a topic of real linking issues (and wonder how it didn't appear in the already existed binding)

No, there is no issue there. This is the same as having two C files including a header with some struct definition, which is equivalent to re-typing the struct in both of these C files. The compiler in C doesn't even store the compiled struct anywhere in the compiled file, it only uses it during compilation to compute offsets and types of each struct member. So, having two C files each defining the struct is the same as having one of those files be in Alusus and defining the struct in Alusus.

**Comment by asmaa899** [comment]
Great, I can then continue building the binding



> Was the raylib binary built by you, or readily available? If you compiled it yourself then you can play with compiler flags to disable struct packing if you want, and that will make the binding more straight forward. But I personally don't think that's necessary.

It's avliable mostly as a shared library for linux (and I assume the binding used with such file), even raylib is zero-dependency library which build can be easily most their other-languages user prefer downloading the binary rather than compiling it

**Comment by asmaa899** [comment]
> Great, I can then continue building my bindings
> 
> > Was the raylib binary built by you, or readily available? If you compiled it yourself then you can play with compiler flags to disable struct packing if you want, and that will make the binding more straight forward. But I personally don't think that's necessary.
> 
> It's avliable mostly as a shared library for linux (and I assume the binding used with such file), even raylib is zero-dependency library which build can be easily most their other-languages user prefer downloading the binary rather than compiling it

**Comment by sarmadka** [comment]
> Great, I can then continue building my bindings
> 
> > Was the raylib binary built by you, or readily available? If you compiled it yourself then you can play with compiler flags to disable struct packing if you want, and that will make the binding more straight forward. But I personally don't think that's necessary.
> 
> It's available mostly as a shared library for linux (and I assume the binding is being used with such a file), though raylib is a zero-dependency library which build can be easy but most other-languages users would prefer downloading the binary rather than compiling, typically.

If it's a zero dependency library, and it's just a single shared object file, then we can simply include the binary with the binding library. That way, the user don't need to worry about downloading anything, and can simply import the Alusus binding in his project and everything will be set.
